##spring Properties profile Local
server:
  port: 8092
  servlet:
    application-display-name: Mutants
json:
  schemas:
    file: c:\java\mutants\deployment\mutant_schema.json
logging:
  level:
    com.skantuz.mutants: debug
    root: info
spring:
  data:
    mongodb:
      database: mutants_db
      port: 27017
      host: localhost