##spring Properties profile Local
server:
  port: 8091
  servlet:
    application-display-name: Mutants
json:
  schemas:
    file: mutant_schema.json
    dir: /app/config/
logging:
  level:
    com.skantuz.mutants: debug
    root: info
spring:
  data:
    mongodb:
      database: mutants_db
      port: 27017
      host: mongodb